trigger:
  - develop

variables:
  - group: 'production'

pool:
  vmImage: 'ubuntu-22.04'

stages:
  - stage: 'test_services'
    displayName: 'Test Services'
    jobs:
    - job: 'api'
      displayName: 'API'
      continueOnError: false
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Test'
          inputs:
            command: 'test'
            projects: '**/*.csproj'
            arguments: '-c Test'
            workingDirectory: '$(System.DefaultWorkingDirectory)/src/tests'

  - stage: 'deploy_services'
    displayName: 'Deploy Services'
    jobs:
      - job: 'api'
        displayName: 'API'
        steps:
        - task: Docker@2
          displayName: 'Docker Build and Push'
          inputs:
            containerRegistry: '$(ContainerRegistryName)'
            repository: '$(ContainerRepositoryName)'
            command: 'buildAndPush'
            Dockerfile: '$(System.DefaultWorkingDirectory)/src/DotNETModernAPI.Presentation/Dockerfile'
            buildContext: '$(System.DefaultWorkingDirectory)/src'
            tags: |
              latest
              $(Build.BuildId)
