version: '3.8'

services:
  dotnetmodernapi_api:
    container_name: "dotnetmodernapi_api"
    build:
      context: .
      dockerfile: DotNETModernAPI.Presentation/Dockerfile
    ports:
      - 3000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  dotnetmodernapi_db:
    container_name: dotnetmodernapi_db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=c86d88854a0a0d8ddf2f73d3f1f70043
      - POSTGRES_DB=DOTNetModernAPIDB
    volumes:
      - 'dotnetmodernapi_data:/db'

volumes:
  dotnetmodernapi_data:
