version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: DotNETModernAPI.Presentation/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - dotnetmodernapi:/api
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=c86d88854a0a0d8ddf2f73d3f1f70043
      - POSTGRES_DB=DotNETModernAPI
    volumes:
      - dotnetmodernapi:/db

volumes:
  dotnetmodernapi:
